runtime: python39  # 使用するPythonのバージョンを指定します。例: python39, python310, python311, python312
env: standard      # App Engine Standard Environment を使用します。

# アプリケーションのエントリポイントを定義します。
# Gunicornを使ってFlaskアプリケーションを起動します。
# main:app は main.py ファイル内の app という名前のFlaskアプリケーションインスタンスを指します。
entrypoint: gunicorn -b :$PORT main:app

# HTTPリクエストのルーティングルールを定義します。
handlers:
# /static/ 以下のリクエストは、staticディレクトリから静的ファイルを直接配信します。
# HTMLファイルからCSSやJavaScriptなどのファイルを読み込むために必要です。
- url: /static
  static_dir: static

# それ以外のすべてのリクエストは、Pythonアプリケーション（main:app）によって処理されます。
- url: /.*
  script: auto

# インスタンスのスケーリング設定を定義します。
# これらはデフォルト値であり、必要に応じて調整できます。
automatic_scaling:
  min_instances: 0  # 最小インスタンス数。0にすると、リクエストがないときにインスタンスが停止し、コストを抑えられます。
  max_instances: 1  # 最大インスタンス数。トラフィックが増えたときに自動的にスケールアウトする上限です。
  target_cpu_utilization: 0.65 # CPU使用率がこの値を超えるとスケールアウトを検討します。
  target_throughput_utilization: 0.65 # スループットがこの値を超えるとスケールアウトを検討します。
  max_concurrent_requests: 80 # 各インスタンスが同時に処理できる最大リクエスト数です。

# 環境変数が必要な場合は、ここに定義します。
# env_variables:
  # SECRET_KEY: 'your_super_secret_key_here'
  # あなたのmain.pyでは app.secret_key="20041007" とハードコードされています。
  # 本番環境では、このように直接コードに書くのではなく、環境変数から取得するように変更し、
  # ここで設定するか、Cloud Secret Managerのようなサービスで安全に管理することを推奨します。
  # 例: app.secret_key = os.getenv('SECRET_KEY', 'default_fallback_key')