runtime: python312  # 使env_variables:
env: standard      # App Engine Standard Environment を使用します。

# アプリケーションのエントリポイントを定義します。
# Gunicornを使ってFlaskアプリケーションを起動します。
# main:app は main.py ファイル内の app という名前のFlaskアプリケーションインスタンスを指します。
entrypoint: gunicorn -b :$PORT main:app

# HTTPリクエストのルーティングルールを定義します。
handlers:
# /static/ 以下のリクエストは、staticディレクトリから静的ファイルを直接配信します。
# HTMLファイルからCSSやJavaScriptなどのファイルを読み込むために必要です。
- url: /static
  static_dir: static

# それ以外のすべてのリクエストは、Pythonアプリケーション（main:app）によって処理されます。
- url: /.*
  script: auto

env_variables:
  CLOUD_STORAGE_BUCKET: "libcararian_storage" 

# インスタンスのスケーリング設定を定義します。
# これらはデフォルト値であり、必要に応じて調整できます。
automatic_scaling:
  min_instances: 0  # 最小インスタンス数。0にすると、リクエストがないときにインスタンスが停止し、コストを抑えられます。
  max_instances: 10  # 最大インスタンス数。トラフィックが増えたときに自動的にスケールアウトする上限です。
  target_cpu_utilization: 0.65 # CPU使用率がこの値を超えるとスケールアウトを検討します。
  target_throughput_utilization: 0.65 # スループットがこの値を超えるとスケールアウトを検討します。
  max_concurrent_requests: 80 # 各インスタンスが同時に処理できる最大リクエスト数です。
  request_timeout: 300s